apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: s2i-test
spec:
  selector:
    matchLabels:
      app: s2i
  replicas: 1
  template:
    metadata:
      labels:
        app: s2i
    spec:
      containers:
        - name: hello-openshift
          image: quay.io/cbanavik/test:latest
          ports:
            - containerPort: 8080
