apiVersion: v1
kind: Service
metadata:
  labels:
    app: s2i
  name: sample-svc
  namespace: s2i-test
spec:
  clusterIP: 172.30.227.230
  ports:
  - name: 5000-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: s2i
  sessionAffinity: None
  type: ClusterIP
